/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0e0e0e",
        "on-surface-variant": "#adaaaa",
        "error-dim": "#d7383b",
        "on-primary-fixed": "#002a35",
        "surface-container-high": "#20201f",
        "error": "#ff716c",
        "tertiary-fixed": "#95adff",
        "primary-fixed": "#00cffc",
        "on-primary-fixed-variant": "#004a5c",
        "on-secondary-fixed-variant": "#005775",
        "on-primary-container": "#004050",
        "error-container": "#9f0519",
        "surface-container-highest": "#262626",
        "on-primary": "#004a5d",
        "surface-tint": "#69daff",
        "surface-variant": "#262626",
        "secondary-fixed-dim": "#6ecfff",
        "surface-container-lowest": "#000000",
        "surface": "#0e0e0e",
        "on-secondary-fixed": "#00394e",
        "on-surface": "#ffffff",
        "primary-fixed-dim": "#00c0ea",
        "on-tertiary": "#00236d",
        "inverse-on-surface": "#565555",
        "surface-container": "#1a1a1a",
        "on-secondary": "#00374c",
        "primary": "#69daff",
        "on-background": "#ffffff",
        "on-secondary-container": "#f1f9ff",
        "primary-container": "#00cffc",
        "secondary-container": "#006688",
        "surface-bright": "#2c2c2c",
        "inverse-surface": "#fcf9f8",
        "on-tertiary-fixed-variant": "#00318e",
        "on-error-container": "#ffa8a3",
        "secondary-dim": "#00b2ec",
        "surface-container-low": "#131313",
        "tertiary": "#89a5ff",
        "on-tertiary-container": "#001851",
        "inverse-primary": "#006880",
        "tertiary-container": "#7696fd",
        "primary-dim": "#00c0ea",
        "secondary-fixed": "#98daff",
        "on-tertiary-fixed": "#001345",
        "tertiary-dim": "#7999ff",
        "on-error": "#490006",
        "outline-variant": "#484847",
        "outline": "#767575",
        "secondary": "#17c0fd",
        "background": "#0e0e0e",
        "tertiary-fixed-dim": "#819fff"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
