// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsStartupRegistered() {
  return window['go']['main']['App']['IsStartupRegistered']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RegisterStartup() {
  return window['go']['main']['App']['RegisterStartup']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartWatcher() {
  return window['go']['main']['App']['StartWatcher']();
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function UnRegisterStartup() {
  return window['go']['main']['App']['UnRegisterStartup']();
}
