// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function IsStartupRegistered():Promise<boolean>;

export function LoadConfig():Promise<config.Config>;

export function RegisterStartup():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartWatcher():Promise<void>;

export function StopWatcher():Promise<void>;

export function SyncNow():Promise<void>;

export function UnRegisterStartup():Promise<void>;
