// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function GetFailedAssets():Promise<Array<main.FailedAsset>>;

export function GetRecentLogLines(arg1:number):Promise<Array<string>>;

export function GetSyncSummary():Promise<Record<string, number>>;

export function IsStartupRegistered():Promise<boolean>;

export function IsWatcherRunning():Promise<boolean>;

export function LoadConfig():Promise<config.Config>;

export function OpenLogFolder():Promise<void>;

export function RegisterStartup():Promise<void>;

export function RemoveExcludedFolder(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartWatcher():Promise<void>;

export function StopWatcher():Promise<void>;

export function SyncNow():Promise<void>;

export function UnRegisterStartup():Promise<void>;
